import { Inter } from "next/font/google";
import "./globals.css";
import SessionWrapper from "./components/SessionWrapper/SessionWrapper";
import "@/app/assets/scss/styles.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Planethive",
  description: "Generated by create Planethive",
};

export default function RootLayout({ children }) {
  return (
    <SessionWrapper>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </SessionWrapper>
  );
}
